#version: "2"
#services:
 # node:
  #  image: "node:22"
   # user: "node"
    #working_dir: /bc2024-6
    #environment:
    #  - NODE_ENV=production
    #volumes:
    #  - ./:/bc2024-6
    #expose:
    #  - "8888"
    #ports: 
     # - "8888:8888"
    #command: "npx nodemon lab5.js --host localhost --port 8888 --cache notes.json"
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8888:8888"
      - "9229:9229"
    command:
      - "nodemon"
      - "lab5.js"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8888"
      - "--cache"
      - "./notes.json"
    volumes:
      - "./:/bc2024-6"
    working_dir: /bc2024-6